version: '2.0'
services:
  ruby:
    build: ./docker/ruby/
    ports:
      - "3000:3000"
    volumes:
      - ./docker/ruby/srcs:/data
    environment:
      FT_TRANSCENDENCE_DATABASE_PASSWORD: password
      TZ: Europe/Paris
    tty: true
    stdin_open: true
  postgresql:
    build: ./docker/postgresql
    environment:
      POSTGRES_PASSWORD: password
      TZ: Europe/Paris
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - "6379:6379"
    volumes:
      - ./docker/redis/redis-data:/var/lib/redis
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
