development:
  adapter: redis
  url: "redis://:sOmE_sEcUrE_pAsS@redis:6379/1"
  channel_prefix: ft_transcendence_development

test:
  adapter: redis
  url: "redis://:sOmE_sEcUrE_pAsS@redis:6379/1"
  channel_prefix: ft_transcendence_test

production:
  adapter: redis
  url: "redis://:sOmE_sEcUrE_pAsS@redis:6379/1"
  channel_prefix: ft_transcendence_production
